### ISSUE TITLE
OAuth null exception handing

### ISSUE THREAD

**Issue by chris98122** [fourseers/PartTimeJob#61]
when a  request header contains { ‘x-access-token’ : null} 
the  response shows {"status":500,"error":"Internal Server Error","message":"status 400 reading AuthService#checkToken(String,String)"}
Backend need to handle this exception and response should contain a message "need to login"

**Comment by eyeKill** [comment]
Plan to fix by adding feign client error decoder to `AuthClient` in gateway.
